#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
import helpers

def main():

    # ensure proper usage
    if len(sys.argv) != 3:
        sys.exit("Usage: ./tweets username (do not use @ before the name) tweets to analyze")
    
    if(sys.argv[1][0] == "@"):
        sys.exit("Error: username must not start with an @. Try again and remove the @ from the username.")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # Get 50 most recent tweets
    
    # loop through those tweets, analyzing and printing 
    
    tweetList = helpers.get_user_timeline(sys.argv[1], int(sys.argv[2]))

    # analyze each tweet
    for tweet in tweetList:
        print("=======================================")
        print("(1) Original Tweet: " + tweet)
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(":)", "green"))
        elif score < 0.0:
            print(colored(":(", "red"))
        else:
            print(colored(":|", "yellow"))

if __name__ == "__main__":
    main()
